"""FastAPI inference service for the Marketing Budget Optimization project.

Serves three endpoints backed by the artifacts produced by `src/train.py`:
  - POST /predict   -> revenue prediction for a given spend allocation
  - GET  /metrics   -> last training run metrics (experiment tracking)
  - POST /optimize  -> recommended budget allocation under business constraints

Run locally with:
    uvicorn src.api:app --reload
"""
import glob
import json
import os
from typing import Dict

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# Imported so joblib can resolve these classes when unpickling the pipelines.
from src.transformers import AdstockTransformer, SaturationRegressor  # noqa: F401
from src.optimizer import optimize_allocation

MODELS_DIR = "models"
METRICS_PATH = os.path.join(MODELS_DIR, "metrics.json")

app = FastAPI(
    title="Marketing Budget Optimization API",
    description="Inference and optimization service backed by end-to-end trained pipelines.",
    version="1.0.0",
)

models_cache: Dict[str, object] = {}


@app.on_event("startup")
def load_models():
    """Loads every `pipeline_*.joblib` artifact into memory at startup."""
    model_files = glob.glob(os.path.join(MODELS_DIR, "pipeline_*.joblib"))
    if not model_files:
        print(f"WARNING: no model artifacts found in '{MODELS_DIR}/'. Run `python -m src.train` first.")

    for filepath in model_files:
        basename = os.path.basename(filepath)
        channel_name = basename.replace("pipeline_", "").replace(".joblib", "").replace("_", " ").title()
        try:
            models_cache[channel_name] = joblib.load(filepath)
            print(f"Loaded model: {channel_name}")
        except Exception as exc:
            print(f"Failed to load {filepath}: {exc}")


def _load_metrics() -> dict:
    if not os.path.exists(METRICS_PATH):
        raise HTTPException(status_code=404, detail="metrics.json not found. Run `python -m src.train` first.")
    with open(METRICS_PATH) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------
class PredictRequest(BaseModel):
    allocations: Dict[str, float] = Field(
        ...,
        example={"Google Ads": 5000.0, "Meta Ads": 3500.0, "Tiktok Ads": 1500.0},
        description="Mapping of channel name to daily ad spend.",
    )


class PredictResponse(BaseModel):
    revenue_by_channel: Dict[str, float]
    total_revenue: float
    total_spend: float
    roas: float


class OptimizationRequest(BaseModel):
    total_budget: float = Field(..., example=15000.0, description="Total daily budget available to allocate.")
    min_roas: float = Field(2.0, example=2.0, description="Minimum acceptable global ROAS.")
    min_share: float = Field(0.10, example=0.10, description="Minimum share of the budget per channel.")
    max_share: float = Field(0.60, example=0.60, description="Maximum share of the budget per channel.")


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/")
def root():
    return {
        "message": "Marketing Budget Optimization API is running.",
        "loaded_models": list(models_cache.keys()),
    }


@app.post("/predict", response_model=PredictResponse)
def predict_revenue(req: PredictRequest):
    """Predicts the revenue generated by a given per-channel spend allocation."""
    revenue_by_channel = {}
    total_revenue = 0.0
    total_spend = 0.0

    for channel, spend in req.allocations.items():
        if channel not in models_cache:
            raise HTTPException(
                status_code=400,
                detail=f"No model found for '{channel}'. Available: {list(models_cache.keys())}",
            )
        prediction = float(models_cache[channel].predict(np.array([spend]))[0])
        revenue_by_channel[channel] = round(prediction, 2)
        total_revenue += prediction
        total_spend += spend

    roas = total_revenue / total_spend if total_spend > 0 else 0.0
    return PredictResponse(
        revenue_by_channel=revenue_by_channel,
        total_revenue=round(total_revenue, 2),
        total_spend=round(total_spend, 2),
        roas=round(roas, 2),
    )


@app.get("/metrics")
def get_metrics():
    """Returns the metrics captured during the last training run (experiment tracking)."""
    return _load_metrics()


@app.post("/optimize")
def optimize_budget(req: OptimizationRequest):
    """Recommends a budget allocation that maximizes revenue under business constraints."""
    metrics = _load_metrics()
    channel_params = {
        channel: data["saturation_params"] for channel, data in metrics["channels"].items()
    }
    result = optimize_allocation(
        channel_params,
        total_budget=req.total_budget,
        min_roas=req.min_roas,
        min_share=req.min_share,
        max_share=req.max_share,
    )
    if not result["success"]:
        raise HTTPException(
            status_code=400,
            detail="Infeasible: constraints prevent an optimal solution. Try lowering min_roas.",
        )
    return result


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("src.api:app", host="0.0.0.0", port=8000, reload=True)
